//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeApp.Mobile.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeApp.Mobile.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Ad Placeholder.
        /// </summary>
        public static string BannerAdPlaceholder {
            get {
                return ResourceManager.GetString("BannerAdPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📂 Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cook.
        /// </summary>
        public static string Cook {
            get {
                return ResourceManager.GetString("Cook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔥 Cook Time.
        /// </summary>
        public static string CookTime {
            get {
                return ResourceManager.GetString("CookTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🥘 Ingredients.
        /// </summary>
        public static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📝 Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No categories found.
        /// </summary>
        public static string NoCategoriesFound {
            get {
                return ResourceManager.GetString("NoCategoriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recipes found in this category.
        /// </summary>
        public static string NoRecipesFound {
            get {
                return ResourceManager.GetString("NoRecipesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏱️ Prep Time.
        /// </summary>
        public static string PrepTime {
            get {
                return ResourceManager.GetString("PrepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prep.
        /// </summary>
        public static string Prep {
            get {
                return ResourceManager.GetString("Prep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try adjusting your search or check other categories.
        /// </summary>
        public static string TryAdjustingSearch {
            get {
                return ResourceManager.GetString("TryAdjustingSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try refreshing or check your connection.
        /// </summary>
        public static string TryRefreshing {
            get {
                return ResourceManager.GetString("TryRefreshing", resourceCulture);
            }
        }
    }
}
